### ISSUE TITLE
Curses::UI::Grid::Cell version is not correct

### ISSUE THREAD

**Issue by shalk** [tupinek/Task-Curses-UI#1]
hi  tupiek, i use the module install curses::ui  and relation modules
I found  Curses::UI::Grid::Cell is not install  correct 

```
$ cpanm Task::Curses::UI
--> Working on Task::Curses::UI
Fetching http://www.cpan.org/authors/id/S/SK/SKIM/Task-Curses-UI-0.01.tar.gz ... OK
Configuring Task-Curses-UI-0.01 ... OK
==> Found dependencies: Curses::UI::Grid::Cell, Curses::UI::Mousehandler::GPM
Found Curses::UI::Grid::Cell 0.14 which doesn't satisfy 0.15.
--> Working on Curses::UI::Mousehandler::GPM
Fetching http://www.cpan.org/authors/id/M/MA/MARCUS/Curses-UI-Mousehandler-GPM-0.01.tar.gz ... OK
Configuring Curses-UI-Mousehandler-GPM-0.01 ... OK
Building and testing Curses-UI-Mousehandler-GPM-0.01 ... OK
Successfully installed Curses-UI-Mousehandler-GPM-0.01
! Installing the dependencies failed: Module 'Curses::UI::Grid::Cell' is not installed
! Bailing out the installation for Task-Curses-UI-0.01.
1 distribution installed
```

I found  the latest Curses::UI::Grid version is 0.15 ,

but the Curses::UI::Grid::Cell  pm file  in the module is only  0.14

see this ( https://metacpan.org/diff/file?source=ADRIANWIT/Curses-UI-Grid-0.14&target=ADRIANWIT/Curses-UI-Grid-0.15 )

I don't know  whether the author of  Curses::UI::Grid   made a little mistake .

I suppose  you can change Makefile.PL

`requires 'Curses::UI::Grid::Cell' => 0.14;`

or 

`requires 'Curses::UI::Grid' => 0.15;`

**Comment by michal-josef-spacek** [comment]
Thanks for report, i create new release now.
